### ISSUE TITLE
define-data-property not listed in dependencies

### ISSUE THREAD

**Issue by alex-saunders** [ljharb/set-function-length#2]
Hi there,

It looks like the package `define-data-property` is currently marked as a dev dependency but it's used in the shipped code. This is causing my CI to fail when it prunes dev dependencies before deploy.

Happy to open a PR for this just don't have the time atm so thought I'd open an issue incase a quick fix possible

Thanks!

**Comment by ljharb** [comment]
Thanks, will be fixed shortly.

**Comment by ljharb** [comment]
v1.1.1 is released.

**Comment by alex-saunders** [comment]
Thanks @ljharb ! Appreciate all the work you do

**Comment by donratta** [comment]
Thanks for the quick patch! @ljharb
